version: '3'
services:
  blog:
      image: qingcc/hexo_blog:latest
      #restart: 'always'
      #ports:
       # - "4000:4000"
      container_name: 'hexo_blog'
      volumes:
        - ~/.ssh:/root/.ssh
        - /root/docker/hexo/source:/blog/source
        - /root/docker/hexo/themes/next/_config.yml:/blog/themes/next/_config.yml
        - /root/docker/hexo/scaffolds:/blog/scaffolds
        - /root/docker/hexo/_config.yml:/blog/_config.yml
      networks:
        docker_net:
          ipv4_address: 172.33.0.10

networks:
  docker_net:
    external: true