version: '3'
services:
  blog:
      image: docker.io/qingcc/hexo_blog:latest
      restart: 'always'
      ports:
        - "4000:4000"
      container_name: 'hexo_blog'
      volumes:
        - ~/.ssh:/root/.ssh
        - /root/docker/hexo/source:/blog/source
        - /root/docker/hexo/themes:/blog/themes
        - /root/docker/hexo/scaffolds:/blog/scaffolds
        - /root/docker/hexo/_config.yml:/blog/_config.yml
      networks:
        - docker_net

networks:
  docker_net:
    ipam:
      config:
        - subnet: 172.25.0.0/16